# Generated by Django 5.0.3 on 2024-03-11 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 2, 5, 32, 835361, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2024, 3, 11, 2, 5, 32, 834728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
