# Generated by Django 5.0.3 on 2024-03-11 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_created_at_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 11, 2, 5, 50, 682136, tzinfo=datetime.timezone.utc)),
        ),
    ]
