# Generated by Django 5.0.3 on 2024-03-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_invoice_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="For item purchased"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2024, 3, 28, 18, 12, 13, 754124, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
