# Generated by Django 5.0.3 on 2024-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_invoice_description_alter_invoice_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
